version: '3'

services:
  debatebox:
    build:
      context: .
      dockerfile: 'Dockerfile'
    image: debatebox
    env_file:
    - ./.env
    volumes: &volumes
    - ./src:/app/src
    - ./examples:/app/examples
    - ./notebooks:/app/notebooks
    - vs_server:/root/.vscode-server
    - cache:/root/.cache  # general cache
    working_dir: /app
    ports:
      - 8889:8889   # this allows to run jupyter notebook on --port=8888
    command: ["jupyter-lab", "--port=8889", "--ip=0.0.0.0", "--allow-root", "--allow_origin='*'", "--NotebookApp.allow_origin='*'"]

volumes:
  vs_server:
  cache: